version: '3.1'

services:
  mongo:
    image: mongo
    ports:
      - 27017:27017

  backend:
    image: jahwag/worksample
    ports:
      - 8080:8080
    environment:
      - spring.data.mongodb.host=mongo
      - spring.data.mongodb.port=27017
    depends_on:
      - mongo

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
